import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { SideMenuComponent } from './components/side-menu/side-menu.component';
import { AuthService } from './services/auth.service';
import { addIcons } from 'ionicons';
import {
  home,
  business,
  logOut,
  person,
  document,
  personCircleOutline,
  card,
  personOutline,
  mailOutline,
  callOutline,
  briefcaseOutline,
  createOutline,
  personCircle,
  peopleOutline,
  locationOutline,
  ribbon,
  informationCircleOutline,
  folderOpen,
  documentTextOutline,
  imageOutline,
  cloudUploadOutline,
  resizeOutline,
  trashOutline,
  refresh,
  close,
  personAdd,
  eye,
  eyeOff,
  documentOutline,
  documentAttachOutline,
  download,
  businessOutline,
  handLeftOutline,
  colorPaletteOutline,
  ellipsisHorizontalOutline,
  timeOutline,
  starOutline,
  storefrontOutline,
  filterOutline,
  pricetagOutline,
  calendarOutline,
  statsChartOutline,
  eyeOutline,
  logoFacebook,
  logoInstagram,
  logoWhatsapp,
  logoYoutube,
  logoLinkedin,
  logoTwitter,
  logoTiktok,
  chevronBackOutline,
  chevronForwardOutline,
  chevronDownOutline,
  locateOutline,
  checkmarkOutline,
  closeCircleOutline,
  closeOutline,
  saveOutline,
  settingsOutline,
  imagesOutline,
  checkmarkCircleOutline,
  arrowBack, 
  closeCircle,
  searchOutline,
  create, trash, logIn, helpBuoy,helpCircle


} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  standalone: true,
  imports: [CommonModule, IonApp, IonRouterOutlet, SideMenuComponent],
})
export class AppComponent {
  constructor(public authService: AuthService) {
    addIcons({
      home,
      business,
      card,
      document,
      logOut,
      person,
      personCircleOutline,
      personOutline,
      mailOutline,
      callOutline,
      briefcaseOutline,
      createOutline,
      personCircle,
      peopleOutline,
      locationOutline,
      ribbon,
      informationCircleOutline,
      folderOpen,
      documentTextOutline,
      cloudUploadOutline,
      resizeOutline,
      refresh,
      close,
      personAdd,
      eye,
      eyeOff,
      documentOutline,
      documentAttachOutline,
      download,
      businessOutline,
      imageOutline,
      trashOutline,
      handLeftOutline,
      colorPaletteOutline,
      ellipsisHorizontalOutline,
      timeOutline,
      starOutline,
      storefrontOutline,
      filterOutline,
      pricetagOutline,
      calendarOutline,
      statsChartOutline,
      eyeOutline,
      logoFacebook,
      logoInstagram,
      logoWhatsapp,
      logoYoutube,
      logoLinkedin,
      logoTwitter,
      logoTiktok,
      chevronBackOutline,
      chevronForwardOutline,
      chevronDownOutline,
      locateOutline,
      checkmarkOutline,
     closeCircleOutline,
      closeOutline,
      saveOutline,
      settingsOutline,
      imagesOutline,
      checkmarkCircleOutline,
      arrowBack, closeCircle, searchOutline, create, trash, logIn, helpBuoy,helpCircle
 
    });
  }
}
