import { addIcons } from 'ionicons';
import {
  // Basic and filled icons
  home,
  business,
  document,
  person,
  logOut,
  close,
  add,
  refresh,
  arrowBack,
  calendar,
  card,
  ribbon,
  ticket,
  pricetag,
  download,

  // Outline variants
  homeOutline,
  businessOutline,
  personOutline,
  personCircle,
  personCircleOutline,
  peopleOutline,
  locationOutline,
  mapOutline,
  calendarOutline,
  chevronBackOutline,
  chevronForwardOutline,
  imagesOutline,
  imageOutline,
  documentOutline,
  documentTextOutline,
  timeOutline,
  shareSocialOutline,
  globeOutline,
  callOutline,
  mailOutline,
  cartOutline,
  bicycleOutline,
  pricetagOutline,
  arrowBackOutline,
  alertCircleOutline,
  createOutline,
  trashOutline,
  settingsOutline,
  checkmarkCircleOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  informationCircleOutline,
  locateOutline,
  checkmarkOutline,
  folderOpen,
  cloudUploadOutline,
  resizeOutline,
  saveOutline,
  filterOutline,
  storefrontOutline,
  closeOutline,
  closeCircleOutline,
  informationCircle,
  logOutOutline,

  // Logos
  logoInstagram,
  logoFacebook,
  logoTiktok,
  logoWhatsapp,
  logoGoogle,

  // Category/extra icons used in Home
  restaurantOutline,
  brushOutline,
  shirtOutline,
  constructOutline,
  hardwareChipOutline,
  medkitOutline,
  fastFoodOutline,
  colorPaletteOutline,
  buildOutline,
  ellipsisHorizontalOutline,
  helpOutline,
} from 'ionicons/icons';

// Registers all Ionicons used across the app.
// Call once from main.ts before bootstrapping the app.
export function setupIonicons(): void {
  addIcons({
    // Basic and filled
    home,
    business,
    document,
    person,
    logOut,
    close,
    add,
    refresh,
    arrowBack,
    calendar,
    card,
    ribbon,
    ticket,
    pricetag,
    download,

    // Outline variants
    homeOutline,
    businessOutline,
    personOutline,
    personCircle,
    personCircleOutline,
    peopleOutline,
    locationOutline,
    mapOutline,
    calendarOutline,
    chevronBackOutline,
    chevronForwardOutline,
    imagesOutline,
    imageOutline,
    documentOutline,
    documentTextOutline,
    timeOutline,
    shareSocialOutline,
    globeOutline,
    callOutline,
    mailOutline,
    cartOutline,
    bicycleOutline,
    pricetagOutline,
    arrowBackOutline,
    alertCircleOutline,
    createOutline,
    trashOutline,
    settingsOutline,
    checkmarkCircleOutline,
    lockClosedOutline,
    eyeOutline,
    eyeOffOutline,
    informationCircleOutline,
    locateOutline,
    checkmarkOutline,
    folderOpen,
    cloudUploadOutline,
    resizeOutline,
    saveOutline,
    filterOutline,
    storefrontOutline,
    closeOutline,
    closeCircleOutline,
    informationCircle,
    logOutOutline,

    // Logos
    logoInstagram,
    logoFacebook,
    logoTiktok,
    logoWhatsapp,
    logoGoogle,

    // Category/extra icons used in Home
    restaurantOutline,
    brushOutline,
    shirtOutline,
    constructOutline,
    hardwareChipOutline,
    medkitOutline,
    fastFoodOutline,
    colorPaletteOutline,
    buildOutline,
    ellipsisHorizontalOutline,
    helpOutline,
  });
}
